### PR TITLE
Moved packages to the impl package

### PR DESCRIPTION
**Pull request by fmarinelli**

### CODE REVIEW

**Comment by cescoffier** [comment]
I think classes from " src/main/java/io/vertx/spi/cluster/jgroups" should stay in this package, as these ones may be used by the user.

**Comment by fmarinelli** [comment]
I think users can only use the JGroupsClusterManager, CacheManager it's for internal use

**Comment by cescoffier** [comment]
Ok, so let's move CacheManager in the "impl" package and keep JGroupsClusterManager in the main (public) package.

**Comment by cescoffier** [comment]
Thanks !

**Pull request merged**
